### ISSUE TITLE
Reducing the file sizes

### ISSUE THREAD

**Issue by lyxell** [jam7/chrome-cross#2]
Has using an utility like `strip` on the final binaries been up for consideration?
http://www.linuxfromscratch.org/lfs/view/6.7-rc1/chapter06/aboutdebug.html
http://www.linuxfromscratch.org/lfs/view/6.7-rc1/chapter06/strippingagain.html

**Comment by jam7** [comment]
It's good idea.  This is a strip trial.  Copied files from ARM7 gcc and perform simple `strip`.
```
-rwxr-xr-x. 1 chronos chronos 79065440 May  3 11:07 cc1
-rwxr-xr-x. 1 chronos chronos 13924464 May  3 11:07 cc1.strip
-rwxr-xr-x. 1 chronos chronos 84924496 May  3 11:07 cc1plus
-rwxr-xr-x. 1 chronos chronos 14997152 May  3 11:07 cc1plus.strip
-rwxr-xr-x. 1 chronos chronos  2619532 May  3 11:06 gcc
-rwxr-xr-x. 1 chronos chronos   715040 May  3 11:07 gcc.strip
```

**Comment by jam7** [comment]
Updated to v1.2.  Now using `strip -S` for glibc223 and `make install-strip` for gcc, binutils and other libraries.  Libraries except glibc223 are not stripped by `strip -S` yet.

**Comment by jam7** [comment]
FYI, I made https://github.com/jam7/chromebrew/tree/update/toolchains branch.  I'll send PR soon if aarch64 is supportted well.
