### ISSUE TITLE
Ruby/git/libssh2

### ISSUE THREAD

**Issue by lyxell** [jam7/chrome-cross#3]
Have you considered building and packaging ruby, git and libssh2 with the toolchains?
It would be nice to have those packages prebuilt and hosted on the same location as gcc for the chromebrew project.

**Comment by jam7** [comment]
I've tried what you want and recognized cross-compiling them in this chrome-cross framework is very difficult.

For example, we need to run perl on chromeos to configure openssl.  Openssl is a part of git.

On the other hand, do you know dockcross?  It is a cross-compiling environment on docker.  It can execute perl for arm on amd64 with qemu.  I'm thinking the way similar to dockcross is much better for this purpose.  It requires chromeos on docker, though.

Or, we can run chromeos or cloudraeady on VM using qemu.  I think this is the best way to build our binary package factory for multiple architectures.  I tried it, but no luck yet.

**Comment by lyxell** [comment]
Wouldn't it suffice to run Perl on the host system? And use the cross-compiler to compile OpenSSL?
https://stackoverflow.com/questions/15539062/cross-compiling-of-openssl-for-linux-arm-v5te-linux-gnueabi-toolchain

**Comment by lyxell** [comment]
This seems to work fine for me, I haven't tested it on a Chromebook, but at least the build succeeds:
```bash
BINUTILS_CHROMIUM_VERSION=release-R48-7647.B
BINUTILS_VERSION=binutils-2.25
GCC_CHROMIUM_VERSION=release-R55-8872.B
GCC_VERSION=gcc-4.9.x
GMP_VERSION=gmp-6.1.2
MPFR_VERSION=mpfr-3.1.5
MPC_VERSION=mpc-1.0.3
ISL_VERSION=isl-0.14.1
CLOOG_VERSION=cloog-0.18.4
CC_VERSION=-cc1.3
GLIBC_VERSION=glibc-2.23
LINUX_VERSION=linux-3.18
CROS_HOST=x86_64-linux-gnu
CROS_KERNEL_ARCH=arm
CROS_PKG_ARCH=armv7l
CROS_TARGET=armv7a-cros-linux-gnueabi
CROS_CROSS_GCC_OPT="--with-arch=armv7-a --with-tune=cortex-a15 --with-fpu=neon --with-float=hard"
CROS_CROSS_LIBC_OPT="libc_cv_forced_unwind=yes"
CROS_NATIVE_GCC_OPT="--with-arch=armv7-a --with-tune=cortex-a15 --with-fpu=neon --with-float=hard"
CROS_NATIVE_LIBC_OPT=""
CROS_HOST_PREFIX=/opt/cross
CROS_HOST_DEST=/dist
CROS_TARGET_PREFIX=/usr/local
CROS_TARGET_LIB="${CROS_TARGET_PREFIX}/lib"
CROS_NATIVE_LDFLAGS="-Wl,-rpath,${CROS_TARGET_LIB}"
CROS_CORES=${NPROCS:-8}

apt update && apt install -y gettext # fix me

PACKAGE_NAME=git

# build zlib
cd /src
wget -q http://zlib.net/zlib-1.2.11.tar.gz && tar xfk zlib-1.2.11.tar.gz
cd zlib-1.2.11
CC=${CROS_TARGET}-gcc ./configure --prefix=${CROS_HOST_PREFIX}
make
make install

# build git
cd /src
wget -q https://github.com/git/git/archive/v2.13.0.tar.gz && tar xfk v2.13.0.tar.gz
cd git-2.13.0
make configure
./configure \
  ac_cv_fread_reads_directories=no \
  ac_cv_snprintf_returns_bogus=no \
  --prefix=${CROS_TARGET_PREFIX} \
  --build=${CROS_HOST} \
  --host=${CROS_TARGET} \
  --with-zlib=/opt/cross/ \
  --without-tcltk
make all
make DESTDIR=${CROS_HOST_DEST}/${PACKAGE_NAME} install
```
Adding OpenSSL in the same way as zlib is added should work fine.

**Comment by jam7** [comment]
@lyxell Thank you very much.  I'll check it out later.

**Comment by jam7** [comment]
Openssl is tough.  It has hard to cross-compile Configure script.

OTOH, I made https://github.com/jam7/dockcross-chromebrew.  Chromebrew emulator on x86_64.  It is slow but work.  I could compile git on that.

**Comment by lyxell** [comment]
What problems do you have when compiling OpenSSL?

**Comment by jam7** [comment]
It tries to compile with `-m64` option since my user land is x86_64.  Therefore, I need to specify target environment as an argument for Configure script, but it supports only armv4 and I'm not sure what I should specify to get the result similar to what I compiled it on native armv7l.  There are several web sites discussing about openssl cross-compile, but those don't help.

Finding an argument for cross-compile is not impossible, but I don't want to do that to all important packages.  It's the reason why I decide to work on https://github.com/jam7/dockcross-chromebrew.  By using that, I can build openssl by just typing `chromeos-armv7 crew build openssl` from host x86_64 system.

**Comment by jam7** [comment]
Well, I figure out correct options to configure openssl.  Now, it contains all of them.  :)

All scripts are available under v1.6 tag.  They at least run on armv7l.  I'll test them.

**Comment by jam7** [comment]
I've moved everything to v1.7 tag.

**Comment by jam7** [comment]
I needed to cross compile not only git but also zlib, openssl, libssh2, curl, expat, ncurses, readline and ruby.  After those, everything run fine now.  :)

**Comment by jam7** [comment]
In v1.8, ruby, git and libssh2 are available for all architectures.  I'll PR soon to chromebrew.
